-- return {
--     "ellisonleao/gruvbox.nvim",
--     opts = {
--         invert_signs = false,
--         inverse = false,
--         overrides = {
--             ErrorMsg = {
--                 bg="none",
--                 fg="none"
--             }
--         }
--     },
--     config = function(_, opts)
--         require("gruvbox").setup(opts)
--     end,
--     event = "VeryLazy",
-- }
